#!/usr/bin/env sh
#V1.1 find socket descriptors
if [ ! $1 ]; then
  echo "Usage: $0 <process name|user|port|IP address|...>";
  echo "shows opened IPv4 descriptors given keyword";
else
  #i[nternet] n[o resove hostnames] P[ort name lookup disable] U[nix sockets]
  lsof -i -n -P -U | grep $1 | grep grep --invert-match | grep "$0 $1" --invert-match
fi