#!/bin/sh
#lans v 2
my_name=${0##*/}

if [ "$my_name" = "lans" ]; then
ifs_list=$(find /sys/class/net -type l -not -lname '*virtual*' -printf '%f ')
fi

if [ "$my_name" = "vlans" ]; then
ifs_list=$(find /sys/class/net -type l -lname '*vlan*' -printf '%f ')
fi

for ss in $ifs_list
do
ifconfig $ss
done